import type {
  AlphaLayout,
  Av1ChunkInspection,
  Av1Codec,
  Binding,
  BindingSource,
  Bitrate,
  ByteRange,
  Canvas,
  CanonicalAssetInput,
  CanonicalChunkPlan,
  ChunkDigestInput,
  CompiledManifest,
  CompiledManifestInput,
  DeclaredLimits,
  Edge,
  EncodedChunkInput,
  EncodedChunkRecord,
  FormatBudgets,
  FormatErrorCode,
  FormatErrorDetails,
  FormatHeader,
  FormatOptions,
  H264AccessUnitSummary,
  H264Codec,
  H264EncoderRenditionPreparation,
  H264ParameterSetSummary,
  H264Profile,
  H264RenditionInspection,
  H264UnitInspection,
  H265AccessUnitSummary,
  Id,
  ParsedFrontIndex,
  ParsedVideoCodecString,
  Port,
  ProductionRendition,
  Rational,
  Readiness,
  Rect,
  ResidencyEndpoint,
  Sha256Hex,
  Start,
  State,
  Transition,
  Trigger,
  Unit,
  UnitBlobRange,
  UnitChunkSpan,
  UnitInput,
  ValidatedAssetLayout,
  VideoBitDepth,
  VideoBitstream,
  VideoCodec,
  VideoLayout,
  VideoRenditionGeometry,
  VideoRenditionGeometryInput,
  VideoStoragePolicy,
  Vp9Codec,
  Vp9PacketInspection
} from "@pixel-point/aval-format";
import { maximumDecodedRgbaBytes } from "@pixel-point/aval-format";

// Never emitted: this tuple makes every canonical wire/video type cross the
// package export boundary during test TypeScript compilation.
export type PublicFormatTypes = readonly [
  AlphaLayout,
  Av1ChunkInspection,
  Av1Codec,
  Binding,
  BindingSource,
  Bitrate,
  ByteRange,
  Canvas,
  CanonicalAssetInput,
  CanonicalChunkPlan,
  ChunkDigestInput,
  CompiledManifest,
  CompiledManifestInput,
  DeclaredLimits,
  Edge,
  EncodedChunkInput,
  EncodedChunkRecord,
  FormatBudgets,
  FormatErrorCode,
  FormatErrorDetails,
  FormatHeader,
  FormatOptions,
  H264AccessUnitSummary,
  H264Codec,
  H264EncoderRenditionPreparation,
  H264ParameterSetSummary,
  H264Profile,
  H264RenditionInspection,
  H264UnitInspection,
  H265AccessUnitSummary,
  Id,
  ParsedFrontIndex,
  ParsedVideoCodecString,
  Port,
  ProductionRendition,
  Rational,
  Readiness,
  Rect,
  ResidencyEndpoint,
  Sha256Hex,
  Start,
  State,
  Transition,
  Trigger,
  Unit,
  UnitBlobRange,
  UnitChunkSpan,
  UnitInput,
  ValidatedAssetLayout,
  VideoBitDepth,
  VideoBitstream,
  VideoCodec,
  VideoLayout,
  VideoRenditionGeometry,
  VideoRenditionGeometryInput,
  VideoStoragePolicy,
  Vp9Codec,
  Vp9PacketInspection
];

// @ts-expect-error fixed-width index codecs remain internal implementation details
export { parseEncodedChunkIndex } from "@pixel-point/aval-format";
// @ts-expect-error canonical byte layout remains private
export type { CanonicalAssetLayout } from "@pixel-point/aval-format";
// @ts-expect-error writer normalization remains private
export type { NormalizedWriterInput } from "@pixel-point/aval-format";

declare const geometry: VideoRenditionGeometry;
// @ts-expect-error public geometry is immutable
geometry.codedWidth = 16;
// @ts-expect-error public geometry rectangles are immutable
geometry.decodedStorageRect[0] = 1;

const pngDeflateCode: FormatErrorCode = "PNG_DEFLATE_INVALID";
void pngDeflateCode;
void maximumDecodedRgbaBytes("h264", 16, 16);
